# Generated by Django 4.0.3 on 2022-03-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ailine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('departat', models.DateTimeField()),
                ('arrivalat', models.DateTimeField()),
                ('totaltime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('totaltime', models.TimeField()),
            ],
        ),
    ]
